/**
 * Type shim for the virtual RSC entry module generated by vinext at build time.
 *
 * The default export is the request handler. Named exports `__assetPrefix`
 * and `__basePath` are inlined string literals from next.config, while
 * `__hasPagesDir` exposes whether the build includes a Pages Router surface.
 * `__imageAllowedWidths` / `__imageConfig` carry the next.config `images`
 * settings so the Cloudflare worker entry can run `/_next/image` optimization.
 * See `entries/app-rsc-entry.ts` for the generator that emits these.
 */
declare module "virtual:vinext-rsc-entry" {
  const rscHandler: import("./server/app-rsc-combined-handler.js").AppRscHandler;
  export default rscHandler;
  export const __assetPrefix: string;
  export const __basePath: string;
  export const __cacheabilityManifest: string | null;
  export const __hasPagesDir: boolean;
  export const __imageAllowedWidths: number[];
  export const __prerenderSecret: string;
  export function __ensureHybridPagesApplication(): void | Promise<unknown>;
  export function __ensureInstrumentation(): void | Promise<void>;
  export const __imageConfig: {
    qualities?: number[];
    dangerouslyAllowSVG?: boolean;
    dangerouslyAllowLocalIP?: boolean;
    contentDispositionType?: "inline" | "attachment";
    contentSecurityPolicy?: string;
  };
}

declare module "virtual:vinext-app-request-entry" {
  type DispatchAppWorkerResponseStage =
    import("./server/app-worker-stages.js").DispatchAppWorkerResponseStage;
  const requestHandler: (
    request: Request,
    ctx: unknown,
    dispatchResponseStage: DispatchAppWorkerResponseStage,
    probeMode?: import("./server/multi-stage.js").VinextCacheabilityProbeMode | null,
    prerenderDiscovery?: boolean,
    trustedPrerenderState?:
      | import("./server/prerender-route-params.js").TrustedPrerenderState
      | null,
  ) => Promise<Response>;
  export default requestHandler;
  export const __assetPrefix: string;
  export const __basePath: string;
  export const __imageAllowedWidths: number[];
  export const __prerenderSecret: string;
  export function __ensureHybridPagesApplication(): void | Promise<unknown>;
  export function __ensureInstrumentation(): void | Promise<void>;
  export const __imageConfig: {
    qualities?: number[];
    dangerouslyAllowSVG?: boolean;
    dangerouslyAllowLocalIP?: boolean;
    contentDispositionType?: "inline" | "attachment";
    contentSecurityPolicy?: string;
  };
}

declare module "virtual:vinext-app-response-entry" {
  import type { AppWorkerResponseStageProps } from "vinext/server/app-worker-stages";
  import type { VinextResponseStageDispatchOptions } from "vinext/server/multi-stage";

  const handler: {
    handleResponseStage(
      request: Request,
      ctx: unknown,
      props: AppWorkerResponseStageProps,
      options?: VinextResponseStageDispatchOptions,
    ): Promise<Response>;
  };
  export const __cacheabilityManifest: string | null;
  export function __ensureHybridPagesApplication(): void | Promise<unknown>;
  export function __ensureInstrumentation(): void | Promise<void>;
  export default handler;
}
